---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lh-authentik-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-authentik-redis
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-authentik-redis
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-authentik
  namespace: networking
spec:
  storageClassName: longhorn
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik
  namespace: networking
spec:
    accessModes:
        - ReadWriteOnce
    volumeName: pv-authentik
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Mi
