---
area/templates:
  - changed-files:
      - any-glob-to-any-file: templates/**/*
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/scripts:
  - changed-files:
      - any-glob-to-any-file: scripts/**/*
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: bootstrap/**/*
area/talos:
  - changed-files:
      - any-glob-to-any-file: talos/**/*
area/taskfile:
  - changed-files:
      - any-glob-to-any-file: .taskfiles/**/*
      - any-glob-to-any-file: Taskfile*
