apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:zOoxioWyzQXtsMtn0Fw6IM0tP1C6t6Tm1gxeBmRajR2v1euL7B9qWXRgBofghvL71GaWlbs7bR2lPNrcfVzleElwFVFQeWcDc9/Z7U4m+XY7W+yUoIPHnP6d3/ZL0h5ObUdZPdSLHBDdwT802Jiam+iR63IJs/QoWQ0dZzTAFpg5z5i/B5Q0iamrVBO20bv4UCQsbpNfRsvPFDvtk+RfyL3PnMZqEau6moFBFDGIfD6RNPhInIbYwqKp+kW+eJVjUVjqe8p0m8pFXRLtWNoY8QD3QwGEHvDHhIXrjsi/q6GmUAUqSDflw0W2t38GdZO4PShGEtHt8CMsCPJkQvtXcytKqAtEm2dxiSejtQ1457GYFWR0P9dAI9KCSiII705HnQ==,iv:hORBJ3w+OV/bnFolHwOAzS7svkyhDWzz7eOfN0ja3Xw=,tag:CUgYCwiWPpbm+K0K3ct0xQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYmhWclRlamhkZDVoNlBt
            aHYrMnkyd1lod1RNdDYvSnBSNGc4azNDSWtJCkJjOVFUbEswRmovUlFmbVkwTytx
            VGNGZkFNTTdQUUI0c2V3MkJ4RDRaYkEKLS0tIHhMMnBpaXIvbnIySVhtRlhVK1hB
            OEV2MWdwTDZ5QTRWTVdiSmRkSFFZZ2sKJf8IUfDA6Lvv4t7c3dsXr6qCf0qoCR31
            OVjP/b47rR61diSLHuS0yg7tkyBG0UIKPuXTbE8xTanVjE4SszWCOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T22:29:04Z"
    mac: ENC[AES256_GCM,data:V+ZAAIifhbCFBRtD2gmxNrOMwhMXJiOz39rCCMhmpYTNUzi2JnggRLx7mOCONnqizfYlem1QXdq1a0xSICU9Cwf2xoaWgyoNb3EfPQSmMGXYEmQBG1D/wVhjfQxHGRZc0ZMY8Z0MbfBa7Qg71ejN97553M43VPWApY9PjkRrB54=,iv:8us2wu/9II4ZJbDJu2LvcwhassVxVt2hZ6nAR9GTMSU=,tag:cn392NOH9zgZuiXUtFCx1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
