[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
UV_PYTHON = "3.12"
KUBECONFIG = "{{config_root}}/kubeconfig"
PYTHONDONTWRITEBYTECODE = "1"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/kubernetes/bootstrap/talos/clusterconfig/talosconfig"
TASK_X_ENV_PRECEDENCE = 1
TASK_X_MAP_VARIABLES = 0

[tools]
python = "3.12"
uv = "latest"
"pipx:cloudflare" = "3.1.1"
"pipx:dnspython" = "2.7.0"
"pipx:email-validator" = "2.2.0"
"pipx:makejinja" = "2.7.2"
"pipx:netaddr" = "1.3.0"
"pipx:ntplib" = "0.4.0"
"aqua:budimanjojo/talhelper" = "latest"
"aqua:cloudflare/cloudflared" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:fluxcd/flux2" = "latest"
"aqua:getsops/sops" = "latest"
"aqua:go-task/task" = "latest"
"aqua:helm/helm" = "latest"
"aqua:helmfile/helmfile" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:kubernetes-sigs/kustomize" = "latest"
"aqua:kubernetes/kubectl" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:siderolabs/talos" = "latest"
"aqua:yannh/kubeconform" = "latest"
