ansible_become_pass: ENC[AES256_GCM,data:X5/66KvlHXvn,iv:zV36myhr0LzFq/aKNMGBd1GyBJWfwC/TR6mK+kJMni4=,tag:rp3vyJhf6MQ439vW6UZkEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K2FLaTM5VU5UZFBsVk5k
            aTQ4dzlDYkhkek9KeGp4R0RRNHJTcTJpbm04CmdzUzZIT0Z2amxyekFMYmZzcHkw
            LzZVQnZNRDlyaHpRc0J1ZER1Wm1yUDgKLS0tIHBoSmxlR0JOcUhwWjY4ditLMEVo
            SG5VU093aEpKc0c1clh4bWJvODBUekEKKkxrtt7hl+cGmel7HsdfMLp53m6LBqZv
            4h3qUowvjj6V063k1VF706uK4uOW4QyfOg3ZpDquwbz9ae1aQ/NMwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T22:26:48Z"
    mac: ENC[AES256_GCM,data:Lz+kmPnUyJJfI9aXMJCcoL/yltA4QT6I4nCUXTEl3H6uSkAAPD9Jl4SLGI1eB40b+NBekFgNuZhfIcEQNvf96wqmEoC54+sKIUxy9iymHWH5LSsSvbZmvpx2Vy2M3o/OfiW4P9m0pIB7e4o6tXoVzG3oxZzC8CdmDbdXYSZ/9iU=,iv:eFFLeKAlofbhR+eCXUxRzv0nma3LkHHV2HJSLEIHG1Y=,tag:aoOvzEvhllbOvPC4xru97A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
