ansible_become_pass: ENC[AES256_GCM,data:nMU9J/JDhyi7,iv:2ZZic1D5aKkz6qfMRHskyG8hg4jAq3GOezdJKBTLXQY=,tag:4xErzDqii26wvARW6EI5FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbUhEcHV6Q1FkR0VISi9w
            cittZEUwYUVYMXhnb2U5cnFTV09FNGNRYmpNCkhSaTZtNStXWnRpWFZ3V2dyM3NY
            WERrUXZhWjJKTDEyQ3VyU3J5WjJsVDgKLS0tIFAzOGhySnBFdExMQ3NyYzlRNmI4
            eUsrUmdUU3grWm9GMm9CNUM4dm14UjQKJuejHlgF6rm826RslvGK5lg2oIEJ3fQ0
            Cwyj9PssmlQhB9Ry4KMxPuA50rFj70RvlJnO7XUijCh3X1T8TKgIlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T22:29:44Z"
    mac: ENC[AES256_GCM,data:jj438hkURVXpxOfhtIfd66JmrtCm6whOe0XN9FZmda6klpmIUBEDSMy6vjyx3CUhTE594m52eA1jRKd4XArUf5Y34uvIMpsD4u6Q/vTsb7KJFEDK4izieE/XhRLN/m55zUCSadnmNq+3GQQV+oZ9Ppf7NZh2WtAqZ0vI9Ees8Ns=,iv:oyA4k1j1djrQIXOUWKUyodGbGvGCAqkySI34iuCGkL0=,tag:jDBnW6zglf2rZO9U2rRcVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
