ansible_become_pass: ENC[AES256_GCM,data:Qls9Z+KwuWkn,iv:+hX8MCIzk0uYviCTlmfJgaNbSoJhTTlbcmFjOEeQv0U=,tag:XcJw7QIsC39OPYCoTVXiMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUU5MSkwzMWo3R29vNWdl
            N3R0RlJxS3V5Q0ltRDd1WHg5aEFiNVFXWlFzCkJqRU1waGVIVEh3ZGRIdVcwcWVh
            WDdtYVkzVEdZaDRiYUcvcGJjQVdrbW8KLS0tIGxrTGtNeThaazE2UlYwdFA2ZWZM
            K2V5ckJFK2FTeklKRmdMMFhRbTIvZ1kKb2oJ7tkR9bcMWa3Xv0C25GBeugenzIT7
            iAWKBqCowPF2sR0dCrYGoyARFMeebx8KNm/adac53BhUZ9Fr2KpWpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T02:05:56Z"
    mac: ENC[AES256_GCM,data:3bzXOQCMcd6Clwf0WNutYk+ZhuMF9aa4VlTP14Nbn8GaavvFwF5H2UwZtHhm80lOoFQVHUYXHmzwQ5KNjiUbhkd7gqPCT5JHX5KS1UF1iXnIRbhqiTzHrEPlGH+Bmfoa/k0HPZukENxRilfrB3kDRz6GBPfC72sffZl5mPgmhyo=,iv:+lqkNeryAN0rt0jHxpA8Awl1LjNJU1bd7z75I2zA9xA=,tag:fwwu/1ztQJEwxwGGTd0W8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
