ansible_become_pass: ENC[AES256_GCM,data:lMCXDSPHfZ3r,iv:mVkjNlmxlAuRtGSPl4V9403PQGxRjYJnjlM7I0I9Eu4=,tag:8fptcaRvAwlwTeZQ91oPOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwekc3NlNycWxnbXVTdDhK
            eDRudkJQbndMNmd0UC9QeSt0WDRBaExIbndzCjJ3R2N3Z2NoQkJoOTBEWGVZWDJk
            akxGckYrVzJnTmJaS0RJY1ZJT0RuTFUKLS0tIHFuQjdYdC95ckprUGpIcnltT1VC
            bEliUGpkL1NiSnlIVDBUSmNNbmd1WkkKjuy5weDKof6R2xi0GjtzfYHEKoIidJnx
            KC06uD3rZhijCywFft0urBi+Aueu9jwMThWTnugKhAk2G1arFwb6GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T22:29:44Z"
    mac: ENC[AES256_GCM,data:8J+PRkxef6dN0jvRksVMTz8cTaap3HYTu3FOR3QNBl6oZ2vz/ctkTm3enjqrqezMrEb5fT0vJDAEKOy+fXVcKPVUFAa3zZ2hRtvo4SpVrcSBgto9l5Ig4M8Gmyxp0oIQXBRYSEUBGSsgxy2q/3BrPP/KN1XIY2WSC4JFRETFpOQ=,iv:blIAdy/xihs2HRnExWcCooLOi47Mk34LWLth+iaeXqk=,tag:uk9RDR5FN/98q6mZWUm+MA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
