ansible_become_pass: ENC[AES256_GCM,data:Dr98LUS1kK3+,iv:CGwyHTqHXx8LRFBJkAJNHc9sME2x0LUbQD/DcVIOTJo=,tag:Jc5kIUupw7JpTKNGsKVZWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d05WL0NySGJWSS9UNzlz
            SXZaRWpJMHZMSkwzS0hQVlhiN1plQ3VWMm44Ci8wdUczTTdRVHpXVGdtazMrbDlV
            eUVzVGREeThzYTNYdG00ZGpEY0NjY00KLS0tIEh6Tk54MFlXV2J2QkV3dEdwbHRu
            SDZscHVGTS9YbUVyRm8ybkpWeUxDTVEKuCpJFZ7fDGWYJFV6wetSBgkcY9M8lZo8
            jewHitV2T10aQgmj+MPOCb5+8kaG7MNg+ZFjluKj0ViHlLzInW63UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T02:05:56Z"
    mac: ENC[AES256_GCM,data:diJFhfnneM5Ju9GnGUVI9styE7lhojI8a9oEsi+XjEWuPqIyEMjqETyiGfBfWRXKFg0Dp3AcS9z9aRQ7mJ+WBIk6L6DWs27Ul4SkrhuYjxkalIaDpzbOJm1lWeHTR5kQCptMIymV9zTXTnvg4v9htFgP0DUgGaRMk6ZQZ2bk9NY=,iv:Rm2lsJah58GJppdFtOlHN72PFIiMVp5phxcUF3m3qMk=,tag:UrmmcQaKznp903ekCgqVyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
