kind: ENC[AES256_GCM,data:S76/14NQ,iv:F5YI3IPvATI6xoKW+6ACN1HxP/rg0pbK4fCFvs3sd0I=,tag:qHslWcb/95Y3FF90NH4xIA==,type:str]
ansible_user: ENC[AES256_GCM,data:C7M3BvcdXucNoyk=,iv:beQySG/IsgcWXUOXGFxL7uYSer+9SOEA8n+fBO7yR8M=,tag:yEVZKpPDGjc+ms3xoYd2qA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ImnyxUOPkK8j,iv:HAHUYYoRmdivrYgILpTYxvWJssbnNiJEl0o1sFrtK1o=,tag:I9eOjNvTL0Kb33/2o4z5XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWWU3Ly9ZeFhHd2hHdTJF
            L2ZnVkc2ak1STGFOWDRrWEdXRTB2a1RGNXpnCnYvTFJCaG1KbDdqVThLSEdVeHdT
            VlF0UjdRTU5SMEpOSlROaFNUdExudnMKLS0tIGhLUkQ0TmhnZkRpTFI5emh3T3Uz
            cmlWR2Q5VWRWTmFpd1JYRDJEL0tYZk0Kf2FgcgSsVg4nYiuPwdO7ZlvNldBOOydn
            LCO5kFTA3L+Pw9V8YvZc/SfgurRy5Fi537KesSvacoaBU8ErBjTMFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T07:17:51Z"
    mac: ENC[AES256_GCM,data:Y0u3Qp14UlMrX7NBIhQ+mIN0E/VclWeuFizDbYlFs+ihFk8DcYnyKrec9wbDHfSe55bdcDi40gQqp2ROX4ca+NwwIyVPccqifVaZZ9FXpqck2YpYs9A6wGPBo4gIG6SrS56XID45i8ks3REHWS2UIsiXu5R5w+WL35pgCydlQPE=,iv:SRDCWDKRSfHv3PuFixpbyynuedU+2LH0mwfyUHfrNGo=,tag:HzXQ5YQr9E5KKG3oc4j9fw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
