kind: ENC[AES256_GCM,data:353m8yr+,iv:l/9ZNzTjTUMVA96XnlFjuzg6cldq4V0d60gWfrmLv8U=,tag:YCyEQ1mJuuPSg9a6NDBnlQ==,type:str]
ansible_user: ENC[AES256_GCM,data:Dzs6D0tQ6kn+rOc=,iv:50qeTmHAEsWit8pXm2mAWRCTVAtja/H4zjIolO8gFJA=,tag:6lN/2q4UQy0/h0z3GyCBIg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qrdYWjnIeqNH,iv:0GTiOwWZ/0CV+wCbhbnNPE8lm37oZEhltx+VZC+Kwrk=,tag:YBnqPv647uA5MMsKahK0eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT2VIbTQ3YSs1WHJBcjhy
            WVJRaU9FaUFzOHhFcklRSytZbEd5M1NlUnlNCnlzRUVDNkpRQUZNbnQrL3RVUDlo
            T1RETHdlOXI0aWpJZmFUZXp0ZC9vdncKLS0tIEJXRGM4dy95YXpqN0xiUnpuNUxG
            U1pGc25vMTdkSlB4UG1DekRwVG5JTmMKkO1c1Z+r5iDg1OXcNx8BFV7gt9nlSuG3
            L7okq5a9DNyG2hxSJICYQdMRs/reK8J3sJK9pL2mrDXWmTPf6Kjoqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T06:21:28Z"
    mac: ENC[AES256_GCM,data:LZUlKWgb3Q1ZPqtXMX0R2pVcyz0dlHCliiS/FiLw0h4UiQOO8E4Z43vhvgOZI10Td20oe+JATnYaWNT3CCaTdblNTn2NRq0afb9847Jf8VLb7CcALCV8Y1LIXOcANc1aGdEY8uFdjwy0PH6R274L2qPzJyBcY5ivyxlGVGuwvPs=,iv:BNNXekEfipWxJMAd4Q/APLYZt+X2Ha4EZLaI/aqwaw4=,tag:8ZJjSV7uZX+BCwUOvYIpmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
