kind: ENC[AES256_GCM,data:bqU1qTQZ,iv:h/C+gG3loLKJDbYQqWmAIGpW5HvSLGQJUiCitP3yOgM=,tag:1OninU4XkELvlcZEZmm53w==,type:str]
ansible_user: ENC[AES256_GCM,data:r+ylpXyobNIgN18=,iv:M36o/R0lGCKBnlif6ymBkSHZ4LoZcJzsETu6Qq/WYuw=,tag:rRmXqVE3EyUjw1J2o9g9ng==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:3N3JP+zqpjsI,iv:zQdjOkPeDV+ecdzc+J/I5+MdbvQqoJ/eJmMTzttmNlM=,tag:HBqvjX2RlAGF1pcK8vN5TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdy9PdWVoWHNyeHVCZ3p1
            c0t3eUpsWHNKSDdmeW90dVhoUk5FN281a21zCllSaVAxb1VYbEtpdDlaZ2VIaVlk
            bnYyYjFnaHFzVDVvNjBvU0RTZHdkY0EKLS0tIFFMU21IZFRrdXlaSldmWnVFeEdw
            NnVlMzBDa2tZTFJYTUlQU0VnMkVQSWsKF6rRsXPth3tQRdx1nYVgmSykucvs0did
            MY0dZPPSbCd3L3lvCpQA22kaf4afr4me8Mo58ttxSHSzvJLTQ51uew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T00:41:35Z"
    mac: ENC[AES256_GCM,data:sTdQ3gJzmkyZ/dlsazqji2nbRuh/azFsl66B+Kzi4l6MrgpoWyxsnp6Se3mw06f8j5ldE56dE30BtFPcJ9DrHhEZvEyDOFxGrJ2jy1+LcXvqtyD0faE/fXbTWQg2d0NLJb8GLtc2RX7tod5LZUREAOdaPQad3A1+GeiBrb8xX0s=,iv:ojLgpGrR2NJvj6glKZPADhd+ELiT4Bxv9mOGZdtO0hE=,tag:QtJGSYXjO+CFkikK/n52Tg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
