kind: ENC[AES256_GCM,data:vvyCuwvv,iv:RoIuneVSk5bOuPJ9i13UcQxCubg7t1/I1L425s8Hm5o=,tag:yrubFudyiuxPi+BGzLwLjQ==,type:str]
ansible_user: ENC[AES256_GCM,data:5B7wHF9JktqNt+g=,iv:MGdoUw4bPQRC0EbANa498PALuZ8C4ISoaj2AIJp1GXs=,tag:kM1gdmplIzoXFb17PstSgA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PcOnQYFFzudC,iv:CaIfqzD51aO/2hzLEUix3xfv2evNslpHJIPZB1p3qDY=,tag:8BFa1TeFxMYQBMD+s4gkXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQzBpS3pKaEh4OFBldVFU
            L1E0ck9TSDlMQlE4MENTOTVZNFhHM1dKNHhzClg5SUluMzM5d3M0aFBnSVZ5eElB
            MWcrdzRHdS9uRVJHdlNCUDE1UXduL0UKLS0tIFdiYXozSWh4SlpVeUF0T2pyamYr
            NmZXb3R3aVZkdkZhOXhNZlpPd21pNkkKlje2TKRnq2/CmASizKzDN6utUWuRDFUw
            MYFIBLM0CPZu1NC+1hXzicoClT8LCVzZ6qyTvZK4p2yxM3NptmIDdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T02:44:43Z"
    mac: ENC[AES256_GCM,data:J/eEtF+6RE9rj/IaRRIYAgXSzz76LhyZk8+4p3gRShH6Y1Lnk/n1ObdgdE/n6B+b2GOcVcwHVcEsEghNfrhmFgRczCQfB4/tcSWle+v/1dEwRHOzRhVvWwcC7eZXK3F3d3sCeaE+yr51sPgvgHX0s/MJT5CHb+NiY7bAnlW+CHo=,iv:CNHGO43RDgJfJp9uB6muAT/kF/n5oX6lnHC+WeZ6yfU=,tag:M4mXI3qd3fMXWB0WSLzN2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
