kind: ENC[AES256_GCM,data:q34nfYLn,iv:fbZ0SbDX51WEcpzzOT4yV4ktM0v1GV96uowIHHLsy5A=,tag:AO+n+tgNNGtQZ9c5UCwrbQ==,type:str]
ansible_user: ENC[AES256_GCM,data:tJtFRF/jT4GCDzA=,iv:JOrEid1ZFnnoq1BpJSrMIP+DJXP03qNpK0HU9myv7EI=,tag:l84/srtrjAQN3VzDVUiAxA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OFFDmYOUnnaG,iv:ArmuI6OJMpucRqYcpxhip6JizzUy1RTzpg9529YaHqI=,tag:Y9VfrD1O6F1fzmqn2Y8VIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYVpaS3MwQ016THM4WHBU
            UTZXWnllcHFBVnlJditrVkc1ZzNac1VtRVNRCmZGbWJ4a0FEU1p0U0VFejVJZVdm
            cXR2S0xnM3Q2ZjFIbXJCY05RYW1Xd3cKLS0tIGJRZ2JVQ3dYakFUS3JsUEpmUW1a
            by9URUVnNCt1RDlqMWV4cUxJQUdTcm8KShywWrUaFJcfzKkKX49j/tUuyCfLTUnh
            9bdvPkuqTNaj54xIFa2GuapZXj62xCU0hHyBkTW8JuIYwb87+uMZOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T02:44:43Z"
    mac: ENC[AES256_GCM,data:OpClTCfu1MVY0cWTGJ3TcQ+vP3M/9EJef4mJy8E3tTcDbK1LQhFWPIukTTRptMwPipFAlcE99vOXh4SlPqaXuGOVq7Ri9DL1SPtLFZ1jmdpsUznFXL3YBqMM63ZNJYiWc6VPGzoxGv4KP8CXFGW1E20klJNCA5ncK5rvLzQf78g=,iv:LIn6mbnS9YRZ7ctP4g5P/OsfLoVqYvqfwEV5wyraiHQ=,tag:xjrwntXPZfd1mqOVZ7xJUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
