kind: ENC[AES256_GCM,data:Nr0ivlvB,iv:u/g2qXscIp9TRSbDUgeYqJQhEeFHcstXlSG2MbC7g/g=,tag:kbylzQbtCibCJWAGbhT99w==,type:str]
ansible_user: ENC[AES256_GCM,data:X/N0LW03zJuP6QY=,iv:KoVeVyE/nrQwBqvvDR+w5zKp3y+XfZ+UGZYXy9pDw08=,tag:qkmDyzwcIcVPebnx71q7mA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:R2zhdYzI7c0x,iv:n41BMjFRqlpg1Oe5pMYYLF+K4ZS9WLlxi6VB/PjEvo4=,tag:+7NkCm5jmdxOPW2LI9NpkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbE9mbXl0TTh3Y3VqNU8z
            NUh6NG9waTQ4dG54eU16MUtueU9GcUNrZGx3CjdHTnFVYWNOVmE0K1UvQ29lSFNt
            b3JnUVBFeGhzeE44VWhLZkIzL3IxV3cKLS0tIFpZdExKMWtNbkNyQXBCNHVqbGZB
            R1ZZZUhSZGl3L3RZSkhTcExhMzE2cjAKZTSG5LzVhaRsLCJCvj9nAMdE6559K12T
            mYeQXayjTIuKkRNDE6UpHw+F01Aj8CLdIg7+5DxkQ42mqzlarbKhjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T00:41:35Z"
    mac: ENC[AES256_GCM,data:NF51bDIoZnIqqy2Sdxt4f/0ta1e58W20ZhS1NAU7pGjh3hLD1dULLo9cyYxtSjn0EUDgF4ngBNku9a7413cchY1mAisSvMgaRGmAzcZId2Wgbd+McGMm0fuOOrexh2puOeq9iKSUDFAUHvetKi1eA9HbWOOrxHDBfMtHSUgft6Q=,iv:CqCKbPDMeD7Xa9s06PhdvjeCGZzAmehhn6LjUor7Sso=,tag:UbG6WVKzcYDq1HffCAwp2w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
