kind: ENC[AES256_GCM,data:eB4tTEqd,iv:/T4WFBJSxgDqJ4zVy1+wR4aNylrCmDkQLgsUL/lmbB0=,tag:wdmhC9EfvXzrp8UlJw2WeQ==,type:str]
ansible_user: ENC[AES256_GCM,data:/lQvm78r36WZwFc=,iv:+iO6DVAxXO/nEJPLKo4p4N6R+JaUZ4oHujM1wc0rCV4=,tag:4rVeEeb+LCLp8T1zKq3Y5Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PUCC7n/3TIeC,iv:VdKEEg1egImCsGuryL29Ip8xbWfKPBjRoa6Aqa0U7gg=,tag:rjL1MKRUORMgY8eVr5YFFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTDd5RmxOMjNaSFE5dDN5
            dUg5eG56QUJBc2NUZUxmREwyU2Y3TjRySVFRCjFncFhmOStHVTduRWl0M2FVUi9h
            MG5IWVk3ekpHR0Vsb2RVQi90UWdKVmMKLS0tIGtDYVEvM0ZhbE42KzRBQS94REpD
            YTlwM05jMlU4MXdYUElZZitXWWo1T2cKZA0+kjRU3B+4AeEXq4ZkH73WHd9XbrS2
            tmme0J23sJGzQeG84HSHCD37P+EjRlSpQ/PnXYGcA+cBl+bxjWZnDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T07:17:51Z"
    mac: ENC[AES256_GCM,data:pEeqlBkAliFumMTMHsJKGFeA0+yeTH4JqN7uEGzejDHJzNiav+V/oKzPBcro8b4+Yge4K3mPYiHUgdC505SayLxTXPghBJ0F4KrR8z2l5kaP47JcuwxLMOLKT+Hw1Po7BPuE52GjxywzHRvp3OD8MIn6OH+iStqtOxeYceT+pZg=,iv:aqr61f3r/k0nvhEMQcO9L7M5HbJPrphS355smve4b1E=,tag:anuaWd7JybO1QbuL5JkkQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
