kind: ENC[AES256_GCM,data:ZfTBwjbi,iv:4up+PVJdhItPCk+43rsRQfes26ctc7pAqz76CkgkTMc=,tag:Ck1DDzN7OCbAv0gEJbz4CQ==,type:str]
ansible_user: ENC[AES256_GCM,data:9KMY+NTV5a5P3sk=,iv:1SZBj0ZJ988Gaa63tWhdRN5GyRBos9Ntvrltg52qsWE=,tag:EVA2wX2k/WcpkhXpMYaRDw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HljDBRhdBFyI,iv:k/ZUUW56gbjQm5gfT7ulvUDX9H22eKqpS6bflpdifLk=,tag:sKU9ZfK0rXyAu1nAWt1GXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQXdLaE95N2xLaTBsb1l4
            Q3ZpcU02TStjTmlpRHpzOWVEcGNJRnFTblVJCnFiS2NSN0twU3YwY3FDeVQrcTl5
            cFMwNDFkbzBibnlNTFYrQjgyaXo4N0UKLS0tIG1nbDQwTUJHMHYxcittVmNsU1pP
            dDRlcFMzaGdKRDgwaWRqaE05UVFFOWMKn3n/mQpqW/XN5gTyB2BqBv76K169Tj3N
            USv7PEE1VAoWPI+TiJveujXCLd3QIMVudVVje2pa0nA4NHBMgipZhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T00:41:35Z"
    mac: ENC[AES256_GCM,data:8rgJskKH38YNLaWPSanFz6xtvjZfxyfxQbMOr3LYl3jcgjEdPdcpEBY9GQ5HfztvB54eJic0Ft0QYHSpZ8FStDgVSztqFZ4IS9lwCzA56I08H0ZGEXcDrHuTh8a5TDjIUj2XPxNcE3j27UMd3e1s4uHqLhh+Sw4QIieTAv42Qp4=,iv:Q0s+Yy2yDotbyCdKFA4ZYAhiK98qdEIl0fF7sECAyLo=,tag:Iau8pnrtTc09LVgyF+sfbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
