---
version: "3"

env:
  DISABLE_TELEMETRY: "true"
  DISABLE_UPGRADE_CHECK: "true"

x-preconditions: &preconditions
  - &k0sctlBinCheck
    sh: command -v k0sctl
    msg: Missing k0sctl
  - &k0sconfigFileCheck
    sh: test -f {{.K0S_CONFIG_FILE}}
    msg: Missing {{.K0S_CONFIG_FILE}}


tasks:

  apply:
    desc: Apply k0s cluster config
    cmds:
      - k0sctl apply --config {{.K0S_CONFIG_FILE}}
      - task: kubeconfig
    preconditions: *preconditions

  reset:
    desc: Resets k0s cluster
    deps: [":ansible:deps"]
    cmds:
      - k0sctl reset --config {{.K0S_CONFIG_FILE}}
      - task: :ansible:run
        vars:
          playbook: cluster-nuke
    preconditions: *preconditions

  kubeconfig:
    desc: Gets k0s cluster kubeconfig
    cmd: k0sctl kubeconfig --config {{.K0S_CONFIG_FILE}} > {{.KUBECONFIG_FILE}}
    sources:
      - "{{.K0S_CONFIG_FILE}}"
    generates:
      - "{{.KUBECONFIG_FILE}}"
    preconditions: *preconditions
