---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1hr
  #url: https://charts.longhorn.io
  url: https://marcomihaicondrache.github.io/longhorn-chart/
