apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:qGJRLNmFisAYqZcsoFEwfWmPwRvSL1LBytfu6lSE13y3rdBHyCsgIjq1Tlrigv+QNwF5S+qHuIv1R9MSv7k/,iv:QyMOL/JBljNg4ubR0PGvV1VJDBL0PpMdwBi/tK/Jick=,tag:5JDuPYxe+sb9jmW5fgTOZA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18f90txv5k2ejeane06d9wzznt2hutjaktdjjgpfdg9yldd2gygnq2sphnu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaDJQWDJuczR4M3FpdE5E
        cTRGcFNOTlNFY0VVTU5CUUN4dEFlMU1EalNRCmp3SHRRYi8zYk9RWVZDelFZRHJ5
        eG8vS1kyYTFONmVDUXJpSTJiTjhWL00KLS0tIHRpSkk4UURXN2RzUWUwWWNPdmo4
        ZmlRRkFQOXlVTEpXN1ZEUzV2VFpXWHMKwU46m6v0kJs7fS12ideSIzNvayK6XfKB
        u/26ZCAEiJDBf9NaJqgZcOMj3pybdrZg9VWJ1aFp6J+GWcIvdHe7HQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-05-02T10:46:21Z"
  mac: ENC[AES256_GCM,data:Q/2ex4Cixgc8C0roalCmguaClHw/Cpz8ZSEmDUFcDPe8G+8uIFsJCmQ6X5BW/fklODRymidpR1dgIOS+Slf9dibj11atooCDFuUSBbsL2avuAmKFrzUVK2enyL9uU0IQiZIwhVI3uPt1V+mqt4xjm7C2F/y2S0QxyfOctxkl0qY=,iv:10PuStMA8UzL8sTRIYY1BjJ+9BQl7otVUlIX/kaBiqM=,tag:DocpQ0tyrwQ8d/qOOa6aAg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.2
