apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:g1KsS42YQEmpFB6JZwVdDxoNIkTEl/GG9ZPVALJIzPyDTFZz,iv:7wN+lG01qzOzVdwyhR/dL/US1GPzN69lS34EpA82Pyc=,tag:pmoCKKT50opgilEZSrrlmw==,type:str]
    credentials.json: ENC[AES256_GCM,data:2u4AqXcR+dVmWIbAAJqoJef4V2kNkvLUeN9IRRlax1MaRBg/fuxGVLYK++vTw85kSdg1hg3ID6Kbrv2DOPoToihDSj8pRE69oGnqGWk0/6LuMZB6JA90a3IoGhaJ3AkzmZBlzM+xSAyXFcUvy/m+821S9ole7aWT/l2l5g5Jkwr8JzRctAJ0gCI+J4iY6YRKcMasZZTWrVteJqKDd7pD0sHoFqToCIyUWmURbFOAwg==,iv:DoQrh5U/uRGwbhFiHt44s9hO5oc6wXuuw/zqdJKEqV8=,tag:ct7SGJXM5Z40J194esxgXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTUllVzAzeThYc0hvd3lj
            WTF1L1NzSUIzM0FKcTAwZVgwci9vcllxS1RrClNSaTZVM1JhTE1BVXZISUJkTnl5
            UzVncmJwbmE1MkZvalE3TVNBT3B2ZnMKLS0tIG45WUZZR0RjWUI1d3RqTStzL1M2
            aVdERFFJcEJnc0F0aEw1cmpBSldISlkK85BwIRytkoINQsqdKnVYD7+OC4vRlQqZ
            Y25Vl1ybimGrdBGTUS5sDouJ7ykpuH+45l0cAmz3ytpUVw7qEfLg4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T22:59:41Z"
    mac: ENC[AES256_GCM,data:QIPKAWMu8Ixf50owH/lBBAZfPJDQ4bUvRRN2wg9kePytl7Xd2/aEFY2kTkVRkZYYVcWnaz4NOOz8FCboijg7ORXyiUn//hB5xaOd2EOH+5lOG6AVF431QfI3PDtQDMcLNeH/J8WVY+aLYbhXTJ18VQhVwBDkOJqjQoBPhARfV5Y=,iv:NPY8rKfydecXf6SgJtnmQZmNDceyT6R8pkgz0Dd/Lzc=,tag:X1mqbOmSFH2nb2SX+S2wgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
