apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:to8XrqAtJiQrj5JgULOclfAAxbjnRA00UHabnPoKk5T6DVBa,iv:TfRc7lzrrzQCa9TBhMoLmjA0KSDHVuncWFzMEdG4NIE=,tag:aY3D8muQ4blPL1ns8yKKNQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:wg6Np4pnjZewepHF2UA9P5agoleqSNBGBD2Fv4CfmJSx1b/kEJtOc3Bldj5CUv/nBL2w9IDEz3kGoXwXHZZ9sQrViJFn5YshmYVxeA0KCo4SG4Fl+HvnDT1RV4CRe8B2WjXgQ3FJ6FDCh7+7DQg/K4LfpraPng3TEItF7LxPR9OP2gx4KqWZv9YLYV7SP26Vslq35cq4zELHIMUJw9K4m93VDFDhNycMBI3kpidFvQ==,iv:c0zMqE7hHihyaQfUz0SB4zXKLoN4bnqsyz+qWPd1+Lw=,tag:even5S/yI9FTrOjDWSeSlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VHk4MlB1WE1ad3lEOFEv
            bWE4SVpsbDVSZkY2cjArZUs4Yk82ZUMrakRJCldFa3ZUZ0hQUVdqajNjVXY0Rndi
            cXBYcXB0cnV2SzNOTjIzUC9BcXcySWsKLS0tIEpBbnd4cWdFbDV5bVU1b2VBOHVZ
            UXozdmxkRUdJdVZteHVtYWZkWTdiVkUKNgvBzqv1E5SxUDGVPDtiFJa/h3nuyqAf
            D6De7BPKxd6y21XU4eMtZpgLt57fsV3O6k+7GwupfOC0uQaD6DH8Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T00:41:29Z"
    mac: ENC[AES256_GCM,data:IrNE22UDV+tgdcZvkge7L2K2DwIk0kXLHuK3UFyrkPEumbzBSJXy87xVDRAMSS5ZniDpyRK3pnZEoJBc0M+oyn9SenzwTPjH+As+eLRDw+ysDhtzrMz0FkMX+UPnJGANpDuXO/AoT6c0TPEc8InUtk26J8BMNG44a8IGFFVgOeY=,iv:y//woc6DwRckJ2TjJBhLgUFqYsyMUzOLDrWpHQ9Gb/E=,tag:Zr7EN758GZ32ArZaXCsI8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
