---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  CLUSTER_SECRET_SOPS_FILE: '{{.KUBERNETES_DIR}}/flux/vars/cluster-secrets.sops.yaml'
  CLUSTER_SETTINGS_FILE: '{{.KUBERNETES_DIR}}/flux/vars/cluster-settings.yaml'
  GITHUB_DEPLOY_KEY_FILE: '{{{{.KUBERNETES_DIR}}/bootstrap}}/flux/github-deploy-key.sops.yaml'

tasks:

  bootstrap:
    desc: Bootstrap Flux into a Kubernetes cluster
    cmds:
      - kubectl apply --server-side --kustomize {{{{.KUBERNETES_DIR}}/bootstrap}}/flux
      - |
        if ! kubectl --namespace flux-system get secret sops-age >/dev/null 2>&1; then
          cat {{.SOPS_AGE_KEY_FILE}} | kubectl --namespace flux-system create secret generic sops-age --from-file=age.agekey=/dev/stdin
        else
          echo "sops-age secret already exists, skipping creation."
        fi
      - sops --decrypt {{.CLUSTER_SECRET_SOPS_FILE}} | kubectl apply --server-side --filename -
      - kubectl apply --server-side --filename {{.CLUSTER_SETTINGS_FILE}}
      - kubectl apply --server-side --kustomize {{.KUBERNETES_DIR}}/flux/config
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.KUBECONFIG}}
      - msg: Missing Sops Age key file
        sh: test -f {{.SOPS_AGE_KEY_FILE}}

  apply-ks:
    desc: Apply a Flux Kustomization resource
    summary: |
      PATH: Path to the Flux Kustomization resource from the apps base dir (required, e.g. default/plex)
      NS: Namespace the Flux Kustomization exists in (default: flux-system)
    cmd: |
      flux build ks {{base .PATH}} \
          --namespace {{.NS}} \
          --kustomization-file {{.KUBERNETES_DIR}}/apps/{{.PATH}}/ks.yaml \
          --path {{.KUBERNETES_DIR}}/apps/{{.PATH}} \
          {{- if contains "not found" .KS }}--dry-run \{{ end }}
      | \
      kubectl apply --server-side --field-manager=kustomize-controller -f -
    requires:
      vars: ['PATH']
    vars:
      NS: '{{.NS | default "flux-system"}}'
      KS:
        sh: flux --namespace {{.NS}} get kustomizations {{base .PATH}} 2>&1
    preconditions:
      - msg: Missing Flux Kustomization for app {{.path}}
        sh: test -f {{.KUBERNETES_DIR}}/apps/{{.path}}/ks.yaml

  reconcile:
    desc: Force update Flux to pull in changes from your Git repository
    cmd: flux reconcile --namespace flux-system kustomization cluster --with-source
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.KUBECONFIG}}

  github-deploy-key:
    cmds:
      - kubectl create namespace flux-system --dry-run=client -o yaml | kubectl apply --filename -
      - sops --decrypt {{.GITHUB_DEPLOY_KEY_FILE}} | kubectl apply --server-side --filename -
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.KUBECONFIG}}
      - msg: Missing Sops Age key file
        sh: test -f {{.SOPS_AGE_KEY_FILE}}
      - msg: Missing Github deploy key file
        sh: test -f {{.GITHUB_DEPLOY_KEY_FILE}}
