apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:uyjokeql8qRazAZyEjQvNqb2GVzg1Yjn,iv:WxuESygrq7o4gl/C609X/0vGlRXlm2EjobFkLU5IG+s=,tag:5eAzknRIsWmq3loj0Wwy/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NTlEakxhWUV4V3R5Rks1
            VW5YclA3N2lkNkR1bVB4ZG4xVmM1Y2E4RjFRCnF6NkxjdXloa2M5Y09KRzQxTFVB
            RGtMQ28yUzBac2tzbThkL0UyZzVZc0UKLS0tIFhrZ21HeEFjb25IVTV5VlNMRTl6
            M1J2Q09yd3FlYTZUWUQ0SGduczNQOHcKXz0q3iT8MVkfNfdlAyJf/+rIi1o9H5u5
            QhPiiT1OJbp6TwsjB2yTAfHHhGBDJEPxTc8ln2JUFH9ZhR+tmRJkLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T22:31:21Z"
    mac: ENC[AES256_GCM,data:g7rYGuoYLbRN0vGtOh5wcuBxhQFcej6oYBzM68f163g/oDhUMPOuYRy7tgHq5bc5OebR2Bmoyi5xd6o47mC7jcvoj3rHoQ2Eh1THRBM6GBNfQ1MBAb6lIJ99+sqYummg+i1uoJCG+xybNg46hhhUFndSEc66ZjRpmgIYmbiDh4c=,iv:pjBrBzjvWPjNNqRx7Tuv7mLXCwrXIqMWz0gOHzdhKVo=,tag:kxvwVTUaGNLoqxu7j5Te3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
