apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FbKaP//IaRMUaAMm3hiV79wpB86ZJOuG3RkJHTG0DiOSfvmJUcDvTQ==,iv:CyxlN0N+6n4p9M5cIqKVmf5p4srznf0O17bZoj+uLxI=,tag:Skh4NCC84Vqyr18wvx4clQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3REczdVR4RlBtZW9WUVNT
            a2o2UlQxbWRMMFNmWEMvdHhpZG5Cak9FUUFnClFKTHBOeno3d1AyWjBlaGV5Q1hP
            aVlnUkN4T2Y5ckkrekQzNmVWaUV0dEEKLS0tIGYwRG1hMFpPK1VVN0ZtQXp1T1Zz
            RnZJSGFHVk5ZbElLQmxPb2doaThuWG8KckHpRWS8kcH8/jFa1BbP9ehPnnIaihUd
            41tZiAMCrQxrs4PPjAodnANZ+9r1nR8JcyK6pNti5+VcSykhrdPadQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T02:23:28Z"
    mac: ENC[AES256_GCM,data:eGSzJP2pGHZzCvdlnA8hDEnM2B6kWP6ik+RflvcmHqVaS8chKVq84+vnZs5opiXAsJgHvJXYdlqfMEU6dJyi5NQWhbaA2Qd0AOvO8TFLQHrZnoHinWOBp47m2YCmdwVcHGqI19ecwvbuXYEmBip9e79/Z34GnzDspsCNWOwRv70=,iv:nAj2xp+frcE0FF9QC1LpPWbnz4xLefRkqyG9F4QWJXo=,tag:a8yZH7ngrDP4PAMwdeL25w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
