---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.42.10
          ansible_user: ubuntu
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.42.13
          ansible_user: ubuntu
