# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:WhROopojkfLYQXL+o4q4PCtGTbKeffEaUIzf3LTdVx3sLu5/cw==,iv:skpc1kuL5/TettT/NnJCZ5dKBcwjV96RhPuiHeQvKTU=,tag:c02El6ZZgVhBjyd16JF36g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb1pDRDlqVE5QRytmQjFO
            R1M1WGFZNlVPZ25xb2R1RnJqYndyVXlPL3g4Ck40bVBzeEk1SkM1OUpkTXNHWU5l
            bE9pNjQ0N1ZVZXRobmlQYVZrU1owZ1UKLS0tIHF2U1U1UEk2akxlbWlnd1E3QnZw
            ODJkQVVYM1UzSDJtaExjNTNhL09RWDgKrCGR34/3Nsl00JxtM4dIJ7yBG19jYLIH
            4d61CR8ANF7/8Ds29hbb7a6iVZ/Qe1bZbjFS95X3uvbjj4heaZ5MQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-31T08:10:22Z"
    mac: ENC[AES256_GCM,data:fwPKqNukq9YdkO/rM8uQezLGVGlo3jTadtuI6GCNZzWilu6fcQS+oZrRPChT+19I6zQ210NWuUwjrQc19HB8UzlRrteDZvK/QQH1SBCd1XvLyfSG7Rz3LiTWvOenkrI9WewKzsq5aGZ5rWwxQoObd036Zx9KUHi5/BLOpWie7Gk=,iv:A92wf49PHD9FBc8Qi7xXRmnXk1Paj4K+FE0+hERHAAQ=,tag:Dfi7DkgCg4SL12eJRxrguA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
