# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9sUeQZ6V+EOyOunubCNHpA==,iv:jcYAXx6PJkuem3LjJdAbGllNAGwCp46ri5e9vmcy+WQ=,tag:4eha/VVB9NZc0eMA2htoEg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kdIgTkR08X4mI4txRHrxY/EeiSVD,iv:T5Jn1+XI9af33PsnHi/szPj6GRIBOpd4IlRUE0stdog=,tag:6GcT2UYHOd9c7jTDoeT28A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMVhBbDhGeEZCVTVCWWd0
            alJadFcwalhsSWJLSEg4bnpyU0FkR3VKSG1JCnY1eS8yRUxvejg3cU5CNStUdHFU
            SVI4dzdHQUpscCsrbklCODFxK0lHbGsKLS0tIDhxdkNyRnNVcy9DNDZGT2dHZUMr
            T0NsRjJDcmo2TjNMZzZPS0ZxSm9QdW8K3Aq/0Vt7pcfH13L0XKVKFtdj6IKYgjjp
            7qR9ko2Dk07nVOdmf0/d9P89hrKSMM6ZVxRJvFnAs2EoK/fZU/jadQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-31T08:10:22Z"
    mac: ENC[AES256_GCM,data:f0v5Y2KEbH57GcbHutNDzVJpVjtNwr9guydJUSHElTphh8kWLKvRvGPHrwZbhqr0RkNzIbd2LKX50/PrXVhQorJrAaeSJir+KDokxuZFwVCdcsMbsilKcG1Kzk+n4efLnljeg/jDtPBRLErOk7Fkulz4YbINXABdm7OpFj3dmFk=,iv:+PXXGx6KD6kxYQQ3QgwOShNkGINMFMxgedeGJ2be/9M=,tag:YlfpWylCPS06gqYMAbnxuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
