apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:uKRiihNuv5lQ,iv:B9fNSK9huIg3usyisfMT1wPofszjzJOK64bf/9vA+YE=,tag:MoImCT4rlx3UwPtg7SqcWQ==,type:str]
    admin-user: ENC[AES256_GCM,data:ThZXLt4=,iv:QwGrja553fdGkp/0r7CTvnQx6gGQpcLxG3998rfEGB4=,tag:bijB+oO6OgZ5glK5rKHzxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSllKbUlYZEpiVGd0VUpR
            dDluMVFqM2l1dmpoZEE2dXBUNUtYcGQ1eDNBCjk4cldNeTMxb3dkTHAvMWFSN1JD
            Qnd2Unc4ekdYaFNlQmd2TU5sN2cyMlUKLS0tIHNlRmJKb2lCaTY5SHkyRWtsRHQ4
            WnVqRGdQc1VjQ283OVg1c1p0N3QxeXMKeiaOzUGxqKli4x2yv2248kG/ElF2CEPF
            m7YZMtx7AYw5Mg1qjUKx5lQClKv2IMrEturaog47d++uYdTYI6/DvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T22:59:53Z"
    mac: ENC[AES256_GCM,data:vDE922TqflXz3lSQQo0LlMZBeqA6wRRVAhs4TNdiPDt2+wrDtBex/sGkmKW1du62hclFQALDOmyHeyVC46Seit+dvRzPmyyGol6Pzguic2D8HnSRPgLzfuKHV87vHoy+vJapJUX9Cp9sUeyAj0mieIrL/bqnRCmzgjPC8hvDjnQ=,iv:TcsFZuaG0TZXiIrtHKLOsYr0OEOHc9S0r+wjw+lhkjY=,tag:1E6JeatuF3Rh5fD+t3lGlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
