---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 18.3.0
  interval: 1m0s
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: metallb
  values:
    priorityClassName: "system-node-critical"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: default
      metrics:
        expose: true
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: ${SVC_TRAEFIK_LB_IP}
