apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:v+kXmCgIUmbJQvE3PetXfvCMNy1bkK0gQYTW9dIa7npJSP1G5w==,iv:5JygDBtMx+EOv7+9P9m5ZvBpzCf+RdmwDzG4YmZJllo=,tag:j5nPRdwZFI7WLuMIApTRLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTDJ1cWNuR1lHcGw4b3BG
            T1pnK2dmTU9paVNqU291SEFxRTNVSi9WMHl3CmxCNEkwcjFCNUdBT3FXVG9PWnpu
            RjdtTEptN0FoUXRYRzYwMko5WDJYNUkKLS0tIHdDcDkwZlI5ZlRUZHZYZnZreG0w
            OUUyVkx4b2drQ09LZ2NtZW9QdzBKdk0KdqaeR0BhsHYTu4CrqE5DhjDYVGy5fhpK
            fZFuZxF83gVL11VXFHc0eCQkQNmWr8hjrzob3xI85+zkmOA23zUv/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T06:21:28Z"
    mac: ENC[AES256_GCM,data:W7cfXHl5+giFmhcpjXQkOqUvxikRyq2M6sD4v4FZQ7NGvFiJQ80ccDMxj+qm09gdAt9EVbww7J8siX3rvgxflNaTnHmSYIVwJEOwxuQ2DwxEKbf++bbc3ELU7O4MGcyq1abcxZpBPvJ0BIOWZ4pnNlDxTHYRHokks0AkrpOqktY=,iv:71P5yly5B6oHbZAzxOVLpuiOKynWzyfbtBvrYmR2ToA=,tag:fTHgIYuYKJ4FdgVxK/rSOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
