apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ut4HfLWuvAmnR+cUJ4/yreYd7RuOQEf7angCU65iiAi82q13eQ==,iv:gY9lV4Ws/XhGFWsc3Jm4jZ/QvG3ou2K9aYOxZaDhTDc=,tag:fyd1xNxzTwhnU8xXtwbQdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdTRGNkRkR2NSNlBIa1Iz
            T01DOFFKUFBkWEFnNzNUOCtCQ0JheTZhUUFJCi9JcmFkSFRUWE9TbVFCTTdKSEJr
            akd6RDcwS0xLcEg5bXhLK2xlUmR3K2cKLS0tIHRWbnJvZ2k4NEppb3ZEVmxscWdw
            eHVUc3JwbU1wcytSTDkwTWlVbm5xQ2sKK2e1zBGDNgeK/jmprKtfirxwQdHbOmAd
            u7SMeP+ceivUCwl9fsiykEHY3st5HH3yQH6dXVve7sBYkHonJRQ3rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T02:23:28Z"
    mac: ENC[AES256_GCM,data:nGaKpZWVwswquVqOLkZOd2THgD2oqAj5omp2cQwxou5ti+qFvMHhaCadyb+vsrJRsi4t+o/r25G+BzgCbA+kh27IOKq2S8dY5JAD99cpcF0cnv80+jQUKf99+lYmRGRCabDEq+RHJ5pooLX5ozy3wFRzGjPeVtWMJH8U+seewv8=,iv:FC7Z1cfwA3cNuHbBbeDpNBrzhXmDDb4G/JyKKlesg0A=,tag:aUhjZ/I7Pe250o9Wl81PGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
