apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:oA+5nYdwFvTo3DrnaN2KJD/h8X92hPxII9gxB9kcXIXJB9l+Si/8Jg==,iv:dEDjEqvb3WXV4+7XqR2JZCh6L8KsqyHl/+OuRkEU6UY=,tag:E9t3gVnPs4NFdP4LRZcCYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWWR3RGVRdzJCa2dMQzVW
            Sm5TQVB3NzdzOWI5VFhTcUErNDhMaXdxaWxNCkErZHJpdEtWVEtSTTFJZ21TT1Rk
            eHV3c2k2UTExM0FST2FCemJDSmViM1UKLS0tIHh3RE9iNU9rVVVidmRpS1JueGJR
            L1JFc3hiTkVoOWRKMXhuckxBSHM3T0EKpA0V1TnAUsuU/IbIU94uiwY/huwA4b66
            7Tm+OsbAzzYiHkUmsutGVtPnHHgHBidbd5jGxy/wsGwGA+w9aaA3kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T22:31:21Z"
    mac: ENC[AES256_GCM,data:wM3qIaey0DjLUvkm+SWcSufwFWBYbDJ6YDthj8EVeUXCrJw4O6X80M5h3eoQpgDaV2wu+BIt1zH4J6q5ncfy6E91sq+o2aODn/qWH4ghMo4PABYKauC9P7kdSSqNpaerGsNx71iEUEXa2rvG/tQ0BJSKoFmZITNaYA9iTPpLW6c=,iv:3a+z+mnms769tDN9LGN3uYgRejuDLXl4xT8koyjfCv8=,tag:eL8Oa8PsRwJPfnRXmBseug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
