kind: Secret
ansible_user: ENC[AES256_GCM,data:9VKsgQ4=,iv:kem13Hg7Fb7DKVB3AHkPlcW4zm1/eI3Xk4AXPxCpCsI=,tag:pqOZbi9bWoR79hZby3iIQA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:gHBy6w==,iv:BcIKjfXNNa7z7XOnquHa8TNqiILTUYmDxK/ATKEnqCQ=,tag:MdmVvnX3XMDaFpa1vFx2lA==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18f90txv5k2ejeane06d9wzznt2hutjaktdjjgpfdg9yldd2gygnq2sphnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M3U3Wm5aMjl2U21BcTh4
            QjJRTmh4b2VRUklKUHZRbmthQWIrVlpwd2hVCmZHRGIzMEh5ekMybjRFNldDQ283
            TXZuVEs0L0NXaHBCWllZRFhpbG5jakEKLS0tIDkzV0V4YjVlZURBcXZIUWMvTXE0
            TzAwb1NTYTZvSEl0d3BMWkVaZENaZTQKDClh65CLHJWslivBUjeasqUhZf1J8ce8
            9GjycxylkHfFiQNy2hdQVRbk0NhXU7B5k1OTEsxxR6M2pwo9OV78uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-30T21:54:09Z"
    mac: ENC[AES256_GCM,data:4mnpaooMU7nYu8l/UZ1zbkfxrYX0KAv+4CiIJyAnbWFR1HFbrbmBMeH0aq4YFhwoDHjZj7MjQo/+dIF1rtIrwjlXnf+gXcigvjAAFL54WpNAyASbxNu/E4NlNxAb6Vv/L2TZbvw7oq6ymUVakpwG9ZoT1JYlk/PWEeuVcvaVcZk=,iv:pW+o/KsM8YlwDykYxYexJi8rtSRyx5QHSFhHL3B+RxY=,tag:87ge6J+x9F33nueAQaDMDA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
