kind: ENC[AES256_GCM,data:bv5gMpOh,iv:2vaeGh3mF7sKSHTbokIXK//BIXHvrKPFBGCIyUFTKG8=,tag:6dzosSpMzeiAR9GDq3xlBQ==,type:str]
ansible_user: ENC[AES256_GCM,data:tt5/iNg=,iv:7VQ0ROCIzoCW3n1iMyKbN9uastGgDTxnq7piMAnyyyE=,tag:aWfGVNn0noPzAtofSeRjAQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:sLPtZg==,iv:RM7bN2KSBWxuJqm2FIY0e39brwIZspGSdgi3hzsm5+c=,tag:GkBkXyb/ZQmwkVmB6gHHYw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-04-30T13:38:46Z'
    mac: ENC[AES256_GCM,data:StVFgroqSPb4S5yxM6t2pc8aXOs1GjpaiZmf8HFYqGOLriesmxsWTJg8BT7k+sadsgbzWSePEoMgdY0+cJl59r9CLlreSrw39VaKg8hCeGXUGEuDvV142iPkWwtA/AVweg9KjNChQ5owdViMRo5OQEn9aWxK+8UzNn+1eALT1pE=,iv:XJaMfZsA0y77uuSFKgrXWuijG+8hr2VLBdLZK9EXeLE=,tag:NV+MkVGma5f0RlQlYT37cg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.4.0
