---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  ARCHFILE: "{{.ROOT_DIR}}/.taskfiles/Workstation/Archfile"
  BREWFILE: "{{.ROOT_DIR}}/.taskfiles/Workstation/Brewfile"

tasks:

  brew:
    desc: Install workstation dependencies with Brew
    cmd: brew bundle --file {{.BREWFILE}}
    preconditions:
      - sh: command -v brew
        msg: Missing Homebrew
      - sh: test -f {{.BREWFILE}}
        msg: Missing {{.BREWFILE}}

  paru:
    desc: Install workstation dependencies with Paru
    cmd: paru -Syu --needed --noconfirm --noprogressbar $(cat {{.ARCHFILE}} | xargs)
    preconditions:
      - sh: command -v paru
        msg: Missing Paru
      - sh: test -f {{.ARCHFILE}}
        msg: Missing {{.ARCHFILE}}

  yay:
    desc: Install workstation dependencies with Yay
    cmd: yay -Syu --needed --noconfirm --noprogressbar $(cat {{.ARCHFILE}} | xargs)
    preconditions:
      - sh: command -v yay
        msg: Missing Yay
      - sh: test -f {{.ARCHFILE}}
        msg: Missing {{.ARCHFILE}}
