---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  brew:
    desc: Install workstation dependencies with Brew
    cmd: brew bundle --file {{.ROOT_DIR}}/.taskfiles/Workstation/Brewfile
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
      - { msg: "Brewfile not found", sh: "test -f {{.ROOT_DIR}}/.taskfiles/Workstation/Brewfile" }

  paru:
    desc: Install workstation dependencies with Paru
    cmd: paru -Syu --noconfirm --noprogressbar $(cat .taskfiles/Workstation/ArchPackages | xargs)
    preconditions:
      - sh: command -v paru
        msg: |
          Paru is not installed. Using ArchLinux?
          Head over to https://github.com/Morganamilo/paru to get up and running.
      - { msg: "ArchPackages not found", sh: "test -f {{.ROOT_DIR}}/.taskfiles/Workstation/ArchPackages" }
