---

- name: Process addon hajimari
  when: hajimari_enabled | default (false)
  ansible.builtin.include_tasks: hajimari.yaml

- name: Process addon grafana
  when: grafana_enabled | default (false)
  ansible.builtin.include_tasks: grafana.yaml

- name: Process addon kubernetes-dashboard
  when: kubernetes_dashboard_enabled | default (false)
  ansible.builtin.include_tasks: kubernetes_dashboard.yaml

- name: Process addon kube-prometheus-stack
  when: kube_prometheus_stack_enabled | default (false)
  ansible.builtin.include_tasks: kube_prometheus_stack.yaml

- name: Process addon weave-gitops
  when: weave_gitops_enabled | default (false)
  ansible.builtin.include_tasks: weave_gitops.yaml
