apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:s9aS3+5VxY3XRibCQoljhfF00ZDorh8tphGTmye57FQsyUcQKYeeZFcstEPPGayz8tcugfFmhYbm45z4,iv:YoZVyIZWI9ui2D80BoP9druOfwkii2faMr3KNeO4TkY=,tag:0SgA9r655gq9x457/hPw/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRkhWc3FIelN4U3Q5Nk4w
            eTZoR0wreis1YmdQNzlqZ3lWdHhFZnFVT0NRCkk5SW1LQTVkdWxVMkRjQnQ5RGUy
            RXZ2Wjl6SE5NVmJtRVpCQ0NNRHl4S3MKLS0tIHYxNHVHUkZVcHVrcWVrR05PWTZr
            R3VzdUFCODQ1VEtxbjd0N1NtRkhVMncKT6NRD2agGY4oqs8gy56YXbyk/113EAHx
            eVJscQJhYkOZXiMS1ju7ycM1ah7BpR1mbNfJXWobNcQg4EvqOxhqhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T00:24:30Z"
    mac: ENC[AES256_GCM,data:ZzP/7+YUo+Uu8c6qN4Kv5LRWcMreppjpFnMmd64+OvbjyqsekIguoaK7G/bGFx50RDvpDK6fsQoSXHgURmA/8aePFs4fXXU/9MwBLuXHpkTOG0q3vOqX7q4lRVaWth6yinNmi0ba/do0bAj66pIQKlCPzoVkmA1TlGFVhvw+iKs=,iv:IOFrPwH47OC2hxyCkdLTYYyYuyMftrT3lRIYlGEyucM=,tag:jOiRkt0v0LGXQd+0xopq3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
