---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    pgp: >-
      ${PERSONAL_KEY_FP}
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      ${FLUX_KEY_FP},
      ${PERSONAL_KEY_FP}
