apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:78EgbskvOtz5T2Q=,iv:rspnYANKbNBtoVpbHKBaLDpurYmMH4L5twjI4XN5LZA=,tag:hSsaRoOWZD1DFGsiUVJu9A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MDPgNcrV8HRwxJmP,iv:GXpjmWKyA37cONXww/+4NedhtIxSuVS6UR3I/g7COqc=,tag:mL1yLBGr65yVUxmhlozNEw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5VD/DTDIm06StkNlExyKerE0bPvhcHP/6weP1DsDvfV8Bd+X,iv:JTKxZQB+FnpISzq9Ei0WUqLaK3uSHQcmXeLT2AHmOBk=,tag:/S0Wjzw5p+4Hy3LNun+7Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bkR1K1BNejYzcnV4SXlY
            UDZtbjJITkd2TkVvWHRvb01pN2ZHS2pyU25ZCkp4MVdaMXF6QVRBdDJ0NmZMZ3Jw
            WWphb1lmeGlsVnRJdGk0Q0tiU3dYUGcKLS0tIFErWWtSc3EzQTVoYWh2QSswc0lH
            WU8yRGlxeWJMUDcyVERxRXdPN00vRTgK8Tb4VIqkVsgjLBYNGnpCo8SYnwYOwSUc
            z1dHoWUk/RVq8vsPIDspHBbRnD63HAcI0ibEwWB923B/wewoom2hLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T07:17:51Z"
    mac: ENC[AES256_GCM,data:ULmHT3dR8+Hvf8VYBjoqBDzUG6rNF1VnQQ7JSvPVqaooUl7RhiBTTQneVGhbe3OtxioMBLQmIB6bZVjDcl4g4qJkDQ73P0jLDLXv1Hp4GV171+psrpw+lZdYP8aD89K6tnhCKFgItyuvYsFKEGyhLbyO/dzOONVhJHIAQJiXaBc=,iv:AJ5pBueNBSLFfXNSR8t2mtfzfVzt22/SvgTzyxxnuoE=,tag:GL7nmAOuB5ajfBt6XNP2zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
