apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:viFO7DeQzOkYP9E=,iv:WuwQclItYQLWo3qOjwkIok6TZrlRK/OU2wp2VWVLMfI=,tag:pLuHY8Yj6GQ/E56X8vB8Pg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ACVFjDbz8FUfwMYr,iv:Iq+5bJuw4Gbyus7Pi2/a5Gzvb76+eoiMDNzOvIm/u90=,tag:iEyM2XyKPGwyBs6g2NDEhg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ju3TiEJrxbucooYodNMR/QOvKSO1BkmH55RcOP1cNwGTfpsm,iv:/XR9aUhMmlQWDB4Mdcy9nSv2qLUdJs0wJVyeObXAaNM=,tag:En/xLCajh7jcWOEIfxBdWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ1VXM3BDdEdEdEhzSzZs
            aXR0NXQ5Qnh3QzBnZUx3SkpORXFTUWpCSUFFCjhuRE1BWnhEb1g3bWcwYU5ZWWQ5
            eHdCK2dsdTB1ei9zeDFZZlFDdGhtUm8KLS0tIGlCZGJQaHVTQThyZlhCQm1LZUVX
            TlpGNXVDb0lrNStmTWl1RWpuK29ZaTQKqx4AshJgMsPl3szvBvf6e8c7USIO9uLA
            zmybIbGoa4smV6BtOb8FGD6nojukCpxwbScd+i8/cT/njeaSrc0Heg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T00:24:29Z"
    mac: ENC[AES256_GCM,data:wSRQcHWVub8gpF3f9vjw59tnITX19FnC0q+IgxA/GT+JC+1sajjfPjBcGUXsg0sQKd32iDb8teOCH7lIwO+82ygBoIGIS7PbyRa1ioJysVg01SAensI05a6dH6PysPBfyADLyVequqocTWvjV6AUBVgSA+KPtBOhd8D705VFJTk=,iv:LxKfolpGUa1CHIyqKY4k+/wLE6oFBpDzSF1WmeqfPR0=,tag:QLam6zP7h9gxQm7gRVW4JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
