---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Toronto"
  KUBE_VIP_ADDR: "10.0.20.40"
  METALLB_LB_RANGE: "10.0.20.20-10.0.20.39"
  METALLB_K8S_GATEWAY_ADDR: "10.0.20.20"
  METALLB_INGRESS_ADDR: "10.0.20.21"
