apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:e1o5+Dd0W9nACZN4Vo7N,iv:agVcJJNluaBEXNeplBExl5TUWI0UPJLZQgbcouNldcY=,tag:TG2DkUjbXKnI9x6j1reFhQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xDd24votVEiUzb1NOt8ulW25l5zjy5HS6mNVFnqe7CFYFcCk,iv:6Hd6ZMR/jzAnAey4sn4iYXs0CzQ8hnhv3OcbEevb2kc=,tag:ZgC4EKI8K95SfITeQV0yLA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:8udEfDlHlKfC,iv:RMct0dZrsS9NY1v03th+9PvapGpOWbZbQD/FNTmJhqU=,tag:NZPk+KeHHBFjXLwXQ1hohA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U2tYOEhHOXZlb1VNaEVq
            VXdneTk3RytlNGZLdkpIVzlJaGRNamlaWDBvCm9Ld1pBaFBBaENqNGNyeGZSaThh
            bHBZVTBxcmVvV0RoNC8wT0hKMVp2cFEKLS0tIGpqVC9XOTdLcFE4VUN6RHF6d00z
            Yyt3VzlTT21SZjNwS3JySmdmbGY5WjAKuAsL3tOoymkJUbBzfFtmDjRZy3zmqB2R
            ALjXTVkFTE3SohKrdTWAXPboGuqJVwdVdbY/tzRpqOzhSE7OKjLHZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T22:28:38Z"
    mac: ENC[AES256_GCM,data:5MST1fjIecx6tHw5oMuOx9etR3Ym7uDEfrG8oMEwAzv7AO2enPlX6FXsX1PDXCR3TDu9pvkAjacn0bMDvU5sDxD0szbjghHq24MzwbkaXGTFndWvFLdBWs6Su9FV8REouq+kRz19lWG52ydBhH02CJ9580khL1GHCXlKecNZ2O4=,iv:8XJ+ohAoTNz+WVpMctDmOmIIQfu+EQER/bAbhB3hV60=,tag:yVKu2bW7opUEa+cjhHhJYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
