---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: ${BOOTSTRAP_ANSIBLE_0_HOST_ADDR}
    worker:
      hosts:
        k8s-1:
          ansible_host: ${BOOTSTRAP_ANSIBLE_1_HOST_ADDR}
