---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: metallb
      namespace: networking
    - name: traefik
      namespace: networking
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    priorityClassName: system-cluster-critical
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    controller:
      replicas: 2
    image:
      repository: cloudflare/cloudflared
      tag: latest
    env:
      TZ: "${TIMEZONE}"
    args:
      - tunnel
      - --config
      - /etc/cloudflared/config.yaml
      - --metrics=0.0.0.0:3333
      - --no-autoupdate
      - run
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        mountPath: /etc/cloudflared/config.yaml
        subPath: config.yaml
        readOnly: true
      # Tunnel credentials setup:
      # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/
      tunnel:
        enabled: true
        type: secret
        name: *app
        mountPath: /etc/cloudflared/tunnel.json
        subPath: tunnel.json
        readOnly: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
      readiness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
      startup:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 30
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
