apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
data:
    TUNNEL_ID: ENC[AES256_GCM,data:YB4cl/0DCTHMhqQXKV2jgmllDdwCqlIY6fykE2pJZ+GPRuyC,iv:HC36cI4BEmIo1H8gr6sIBAVervft0hJ2X+WtUZg24dg=,tag:yoTy6dKB/zY0jdR8boIRJw==,type:str]
    credentials.json: ENC[AES256_GCM,data:FYv93PAQPYOGjs6Oww+z4VSMPqfFnKhQUP1dgQnj2XuPE3Uz39TQJ4vLZfrVO6v/Ol02qCG3T/Gbn2mJWwqrdq8ISiclneuFQvjAhnqIbjuQs/V1Iq0rTetHIf/hWd9jLg7Uz91IM0a+WoQJV1Lc1OS8pAX0avaZtk7q3WLmneu3POwzat9f5PCWsSpmhb3wHOlUFbFbqa2nzRKNYRYJEstTLdERHD84KwGplwL8Iw==,iv:aj0PlC7XGD0B0Wuxmckk6c6gY5bJ0QE5lAV5q4sytlY=,tag:LFNGOJWDbN23tRsUE/MfWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZnVlR0lXMG5kM1h1U0dU
            a0o2Qlc1cEkwcnR0eVdlVmUyeTVXdFR4cldFCmhQTVFkekRTb1RUeDZhR3JiUEZ5
            Y1pXNHRhcjdhMW1GeDRSTCswVExXQTAKLS0tIDV0akdNRi9tNGdSUkExajZlWUpZ
            RFVmT20walc4dDBSanZPcklHUkpiMkkKAFoDqgzm2nUmcxOs4NOgNZwezjpAt47R
            fs6YaPd6mml2xkaO1IQ1qXiH38IGL4xwvuh8q8gq1l4mIrOSU0g3rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T02:23:28Z"
    mac: ENC[AES256_GCM,data:2u9BXcBzHwhlmXn27LNbWToSSwrh4chTNiBuSNy0JidZLp2CzD+R3FO9XmCOX2dk8905H89//bryTMHAmr4UQUy+Rxquf65gNsdp/934nvpom0kJ+MZOIQk0IAn9hx8BL6Zt5XyJwdsayuZgMWPVU/RG3LvbEPCDvXqqOBd7HG0=,iv:UT63HVgj7RCf8afiejVGNUinj9+ME9DXAY8/t/OtQCw=,tag:9CymxLR1I7FUL9dU3slXMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
