apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
data:
    TUNNEL_ID: ENC[AES256_GCM,data:dtX3apPQIQOhQcCTizwrZMJ1zH4aanB+pR3K896+u7b8bulm,iv:5IIBjUpdtHJG6uUXKb5M1bdYmztT+DT8MVeRFJgMKx8=,tag:YorNFOK+mJi/aSXk60Q6Lg==,type:str]
    credentials.json: ENC[AES256_GCM,data:NkQQVnZkHvb1Jn17WJiFjTzMD/EFbIpNpAokFlUA4lJW1DSyoUYCWaGUo8p6N9IO+4Yzs6jViAFtjvnJ6SQaUDTBhYWDx+Ge4GllIQABAE0XNYDvKV2qT1GcZ3Up1aIXOkoZ/+rcbrMRdeujxyi74CcrMiJqH9ndYX9fAks+ONBZRDf/Zn2G59+6KRKfd9cO2DhPa5IrblpB1BXAJ+z9SSoK1N16vondJsk7MnQrWw==,iv:ioXXvOQPkvtLlyWUJPTLnLegaOur96uYMVT1OGZe8Bo=,tag://MExq9xM93ChD+Ay/bSJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxgpxhzdu4xmx83eyen6kl7w7lx0gwfyttyp6nf30w6x7n0yd4mskzfz7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Ky9OZ3VPdW9Ha3ZkSTJn
            VnltTkpRTzNLU0Vjc0RDdmNqU2RGb3BVRlVNClFQWXJRRGxqODI0djI1QlMvRjQv
            RktJV0pxOFltekd2aHNub1pZa2E2RzAKLS0tIExDV1pUcHFCcjRoK3NrRTZlRXNh
            OUVMbU9LYUVMZzliRE5nZFU4U0lYNTgKCWDzzXSOQvqbKLH/c9wblZGkrumZjS7N
            5P5kMgfMLlM2xlfKPA0NqQ817rl8obPvR9AqvdkqyOhbX1gAO1iJDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T02:44:43Z"
    mac: ENC[AES256_GCM,data:FnsIaG0Hksapw/iRL1sUqlOJLvLtxWYsVlaEFgJWV4YAd1g0lnO5n0VEZp3t3PWnht9bHw9dtWJ8wQka3t80HakgLrlvaenkiXTbEvodiXetAxuWCngBDCd0geDifkCFBVFDGY24mb6rVbutX76q5/fvJ4BHu8IO1DHiOpoNlqg=,iv:JjMt++kSRelO+F50lFHbOyt2OethxUC+b3Xdjqu3emM=,tag:iPtixEepNRBSHznzet+LwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
