apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt
  namespace: home
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: "${BOOTSTRAP_SVC_ZIGBEE2MQTT_USER}"
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "${BOOTSTRAP_SVC_ZIGBEE2MQTT_PASSWORD}"
