apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:O0AcspBSpIPGzqn7PGLC/68boo4x69a7AUZKZ9exbM0NycVScgK6sw==,iv:N+DyBdgDv6v2wLmz5VvL2hPfSsfu2FfuG6nho9f1kXw=,tag:i9TWqRE0he/dPXexHMyWRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age132t4ywly2m90awm68kc2wk6wa9lda5mgyh6m6f0a6avfrmu0hygq2wkpt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ2orVEJMTGhNVDREei9H
            UjBGTGRkVTFwcGh2REJjYTFvOWs4bmU3Sm44CjdzMnpWRGpWejQ2Tm9US2o2eE8r
            WVlOOTh1bUU4SkVSRVpyNWNJOWk3ZUUKLS0tIHBQcjVjZG9oMG5DMXkxOWZDazJu
            MWxuY3ZOL2VuRWZDR1BMWm1Fak5FRlUKSv7rrocqqTKz3PI0ZKaw4y/0qB1dayTI
            x0aWjSMUs8w4kqf0EG5h9fy2b3jS/RqhcMc4a/Ik4NkbIOPsOoLW7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T22:31:20Z"
    mac: ENC[AES256_GCM,data:MXJQ6TEQNuMx2P/b19SSBib9VUklfByFv9dncje0r+hXnJ/SCQvnLR6qzFhS046hi+l5ZgZtefoYxjSHmktq5sk1EyS/PyyiZ9ra90lvzdyL+xGNyF7rzIV/j1E6vWSnq5DD8IYweNt240rSormSEEYmPNpu0VVrTemcoTMGj0M=,iv:s+vEcnD85qrpW0WhjlpJfi+MSAaywEM6DJ1V8/DxBwI=,tag:1cB0t/AL095iXpThgZN4LA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
