---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "${BOOTSTRAP_TIMEZONE}"
  METALLB_LB_RANGE: "${BOOTSTRAP_METALLB_LB_RANGE}"
  SVC_TRAEFIK_LB_IP: "${BOOTSTRAP_SVC_TRAEFIK_LB_IP}"
  SVC_LONGHORN_LB_IP: "${BOOTSTRAP_SVC_LONGHORN_LB_IP}"
  SVC_EMQX_LB_IP: "${BOOTSTRAP_SVC_EMQX_LB_IP}"
  SVC_HOME_ASSISTANT_CODE_LB_IP: "${BOOTSTRAP_SVC_HOME_ASSISTANT_CODE_LB_IP}"
  SVC_HOME_ASSISTANT_LB_IP: "${BOOTSTRAP_SVC_HOME_ASSISTANT_LB_IP}"
  SVC_ZIGBEE2MQTT_LB_IP: "${BOOTSTRAP_SVC_ZIGBEE2MQTT_LB_IP}"
  SVC_NODERED_LB_IP: "${BOOTSTRAP_SVC_NODERED_LB_IP}"
  SVC_WEAVE_GITOPS_LB_IP: "${BOOTSTRAP_SVC_WEAVE_GITOPS_LB_IP}"
