---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "e2e"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:

  configure:
    if: ${{ github.repository == 'onedr0p/cluster-template' }}
    name: configure
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config-files:
          - talos
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mise
        shell: bash
        run: brew install mise

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install Python dependencies
        shell: bash
        run: uv pip install --requirement requirements.txt

      - name: Run Sops Age key task
        shell: bash
        run: task bootstrap:age-keygen

      - name: Run init tasks
        shell: bash
        run: |
          task init
          cp ./.github/tests/config-${{ matrix.config-files }}.yaml ./config.yaml
          export BOOTSTRAP_AGE_PUBLIC_KEY=$(sed -n 's/# public key: //gp' age.key)
          envsubst < ./config.yaml | sponge ./config.yaml

      - name: Run configure task
        shell: bash
        run: task configure --yes

      - name: Run clean
        shell: bash
        run: task bootstrap:clean
