---
name: "e2e"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.12"

      - name: Cache venv
        uses: actions/cache@v3
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt', 'requirements.yaml') }}
          path: .venv

      - name: Cache Homebrew Packages
        uses: actions/cache@v3
        id: cache-workflow-tools
        env:
          cache-name: homebrew-packages
        with:
          path: $(brew --prefix)
          key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.taskfiles/Workstation/Brewfile') }}

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - if: steps.cache-workflow-tools.outputs.cache-hit != 'true'
        name: Setup Workflow Tools
        shell: bash
        run: brew install go-task

      - if: steps.cache-workflow-tools.outputs.cache-hit != 'true'
        name: Install Brew dependencies
        shell: bash
        run: task workstation:brew

      - name: Initialize Direnv
        shell: bash
        run: direnv allow .

      - name: Initialize Sops Age key
        shell: bash
        run: task sops:age-keygen

      - name: Install Ansible dependencies
        shell: bash
        run: task ansible:deps force=false

      - name: Generate bootstrap config file
        shell: bash
        run: |
          task init
          cp ./.github/tests/config.yaml ./bootstrap/vars/config.yaml
          cp ./.github/tests/addons.yaml ./bootstrap/vars/addons.yaml
          export BOOTSTRAP_AGE_PUBLIC_KEY=$(sed -n 's/# public key: //gp' age.key)
          envsubst < ./bootstrap/vars/config.yaml | sponge ./bootstrap/vars/config.yaml

      - name: Run configure
        shell: bash
        run: task --yes configure

      - name: List Hosts with Ansible
        shell: bash
        run: task ansible:list

      - name: Run repo clean and reset
        shell: bash
        run: |
          task repo:clean
          task --yes repo:reset
